import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/nord.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
decorations = "None"

[font]
size = 11

[font.normal]
# family = "GohuFont 14 Nerd Font"
# family = "M+CodeLat60 Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Mononoki Nerd Font"
# family = "Hack Nerd Font"
family = "JetBrainsMono NF"
# family = "Agave Nerd Font Mono"
# family = "ZedMono Nerd Font Mono"
style = "Regular"
