# add color scheme
# set -g default-terminal "alacritty"
set -g default-terminal screen-256color
set -ag terminal-overrides ",alacritty:Tc"
set -s escape-time 0

# vi keybindings
# set window-options -g mode-keys vi

# resizing keymap
#bind-key -r -T C-Up    resize-pane -U
#bind-key -r -T C-Down  resize-pane -D
#bind-key -r -T C-Left  resize-pane -L
#bind-key -r -T C-Right resize-pane -R
