# add color scheme
# set -g default-terminal "alacritty"
set -g default-terminal screen-256color
set -ag terminal-overrides ",alacritty:Tc"
set -s escape-time 0

# vi keybindings
# set window-options -g mode-keys vi

