#!/bin/bash

fonts=(FiraCode JetBrainsMono ZedMono)

version='3.2.1'
fonts_dir="${HOME}/.fonts"

if [[ ! -d "$fonts_dir" ]]; then
	mkdir -p "$fonts_dir"
else
  echo "wtf"
fi

for font in "${fonts[@]}"; do
	zip_filename="${font}.zip"
  zip_filepath="${fonts_dir}/${zip_filename}"
	download_url="https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/${zip_filename}"
	echo "Downloading $font from $download_url"
	wget -P "$fonts_dir" "$download_url"
	unzip "${zip_filepath}" -d "$fonts_dir"
	rm "${zip_filepath}"
done

fc-cache -fv
