#!/bin/sh

x=$(echo "poweroff\nreboot\nsleep" | dmenu -p "Exiting...")

case $x in
    poweroff) sudo systemctl poweroff;;
    reboot) sudo systemctl reboot;;
    sleep) sudo systemctl suspend;;
esac
