#!/bin/sh


case "$1" in
    lock)
        i3lock --color $2
        ;;
    exit)
        i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want
             to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'
        ;;
    suspend)
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "You messed up!"
        ;;
esac
exit 0
