#!/bin/sh

version='1.22.4'
tar_filename="go${version}.linux-amd64.tar.gz"
url="https://go.dev/dl/${tar_filename}"

wget $url
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf $tar_filename
rm -rf $tar_filename
