#!/bin/bash

if  ! command -v cargo > /dev/null 2>&1; then
  ./install_rust
  rustup override set stable
  rustup update stable
fi

sudo dnf install cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++

usr_src_dir="${HOME}/.local/usr/src" 
mkdir -p "${usr_src_dir}"
cd "${usr_src_dir}"
git clone https://github.com/alacritty/alacritty.git
cd "./alacritty"
cargo build --release

sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database
