#!/bin/sh

# sudo dnf group install "C Development Tools and Libraries" "Development Tools"
# sudo dnf install cmake -y
# sudo dnf install ocaml opam -y
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
opam init
eval $(opam env --switch=default)
opam install odoc utopW
