#!/bin/bash

./install_rust

usr_src_dir="${HOME}/.local/usr/src"
if [[ ! -d "${usr_src_dir}" ]]; then
	mkdir -p "${usr_src_dir}"
fi

cd ${usr_src_dir}
git clone https://github.com/gleam-lang/gleam.git --branch v1.3.2
cd gleam

make install
sudo dnf install elixir erlang
