export ZSH=$HOME/.oh-my-zsh

export BROWSER="zen"

export TERMINAL="alacritty"

export EDITOR="nvim"

export DOTFILES=$HOME/.dotfiles
export LOCAL_SRC=$HOME/.local/src
export DOTNET_CLI_TELEMETRY_OPTOUT=true
export DOTNET_HTTPREPL_TELEMETRY_OPTOUT=true

export MYVIMRC=$DOTFILES/nvim/init.lua
export MYVIMRC_PARENT=$DOTFILES/nvim/

export GOPATH=$HOME/go/bin
export GOPATH_BIN=/usr/local/go/bin

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"

export PATH=$PATH:$HOME/.dotnet/tools
export PATH=$PATH:$XDG_CONFIG_HOME/npm-global/bin
export PATH=$PATH:$DOTFILES/script
export PATH=$PATH:$HOME/bin:/usr/local/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/usr/bin
export PATH=$PATH:$HOME/.local/share/nvim/mason/bin

typeset -U path
export PATH
